//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chugunova_Bychok.Windows
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int ID { get; set; }
        public string l_Name { get; set; }
        public string f_Name { get; set; }
        public string logim { get; set; }
        public string password { get; set; }
        public double weight { get; set; }
        public double height { get; set; }
        public byte[] photo { get; set; }
        public System.DateTime dob { get; set; }
        public Nullable<int> age { get; set; }
        public int ID_Gender { get; set; }
    
        public virtual Gender Gender { get; set; }
    }
}
